### ISSUE TITLE
Change font size of disclaimer at top of French FAQ so same size as the other text

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/faq#13]
This text:  Creative Commons ne fournit pas de conseils juridiques. Cette FAQ est à titre informatif et ne constitue pas un substitut à des conseils juridiques. Elle peut ne pas porter sur des questions importantes qui vous touchent. Vous devriez consulter votre propre avocat si vous avez des questions.

**Comment by mattl** [comment]
What kind of text is this? Right now we treat it like a blockquote.
