### ISSUE TITLE
French FAQs: additional formatting fixes

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/faq#14]
(1) Capitalize the word "les" at the beginning of this FAQ: les organisations gouvernementales et inter-gouvernementales peuvent-elles utiliser des licences CC ?

(2) Change font of this text so same size as text just above it: "CC offre des données sur les meilleures pratiques pour le marquage de votre matériel et sur la façon de marquer les matériels dans différents médias."

(3) Change font of example notice text so same size as other text in the answer to the FAQ:  "« Le texte et les illustrations de ce document sont autorisées par Red Hat sous une licence non-adaptée Creative Commons Attribution - Partage dans les Mêmes Conditions 3.0 (“ CC-BY-SA “). . . . Red Hat, Red Hat Enterprise Linux, le logo du Shadowman, JBoss, MetaMatrix, Fedora, le logo de Infinity, et RHCE sont des marques de Red Hat, Inc., déposées aux États-Unis et dans d’autres pays. Pour les lignes directrices sur les utilisations autorisées des marques de Fedora, consultez https://fedoraproject.org/wiki/Legal:Trademark_guidelines"

(4) This text, "Vous devez également indiquer si vous avez" is in large font, and is actually the beginning of the sentence that is continued on the next line. Change font size and join with rest of sentence.

(5) Remove html code (####) appearing in this section: Puis-je utiliser des mesures techniques efficaces (tels que les DRM) quand je partage le matériel sous licence CC?

(6) This FAQ is in larger font size than other equivalent FAQs within the section, harmonize: Qu’advient-il si l’auteur décide de révoquer la licence CC qui s’applique sur du matériel que j’utilise ?

(7) Same as (6), for this FAQ: Quels sont les droits sui generis  sur les bases de données?

(8)This text, "CC ne recommande pas l'utilisation de ses" is in large font, and is actually the beginning of the sentence that continues on the next line. Change font size and join with rest of sentence.

**Comment by mattl** [comment]
Fixed in https://github.com/creativecommons/faq/commit/9a04b852072d41f822abfd2fc7d5a1fb20acf165

**Comment by mattl** [comment]
Only 1) was done.
