### ISSUE TITLE
Fix broken links in English FAQ

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/faq#19]
The links in this text are broken (see bolded, italicized text where links exist but are broken):

If you're looking for legal advice about using CC licenses and other tools, we recommend contacting the **_Creative Commons affiliate in your jurisdiction_**. CC affiliates are highly connected to the communities of copyright lawyers in their countries. We also offer a **_list of lawyers and organizations_** who have identified themselves as willing to provide information to others about CC licensing issues.

**Comment by mmoreshead** [comment]
Hey Diane, it's a known issue, lots of broken links in there, I'm working my way through them (slowly).  You can see here: https://github.com/creativecommons/creativecommons.org/issues/197
