### ISSUE TITLE
Remove references to CC Affiliates

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/faq#25]
There's a lot of references to the Affiliates and we should change that for a language more connected with the CC Network.

@simeonoriko can work on updating information there regarding CC Chapters and Network Platforms

**Comment by kgodey** [comment]
Please update the repo and make a pull request, we'll merge and deploy changes.

**Comment by clc80** [comment]
Hello, 
This is an issue that still needs to be be worked on?

**Comment by kgodey** [comment]
Yes but I'm not sure if it's open to non-CC staff, @claudioruiz?

**Comment by claudioruiz** [comment]
It's not necessary.
