### ISSUE TITLE
Insert all links in the French FAQ

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/faq#3]
Insert all links in the French FAQ

**Comment by mattl** [comment]
We don't have the links. The links in the original document all link to the English version.

**Comment by peterspdx** [comment]
The deal with the funder was that we wouldn't translate the content at the other end of the links. But we'd still include links to the English info on the other side. Make sense?

**Comment by mattl** [comment]
This will take some time, as it'll mean going through the document and reinserting them one by one.

**Comment by peterspdx** [comment]
Understood, and appreciated. I alerted the funder it may be several days into next week. I can help with this also incrementally to pitch in.

**Comment by mattl** [comment]
I'm out most of next week, so it may be early next year at this point.

**Comment by ifylala** [comment]
Hello @kgodey I am an Outreachy applicant. I would love to work on this issue.

**Comment by mmoreshead** [comment]
I'm not sure this is suitable for an Outreachy project given that the English FAQ is likely going to get a redesign. This isn't a great issue to take on until that is done.

**Comment by kgodey** [comment]
This ticket is not tagged "help wanted" or "outreachy" and is not suitable for contribution.

**Comment by ifylala** [comment]
Thanks so much @kgodey
