### ISSUE TITLE
Create page with 10 most important FAQs

### ISSUE THREAD

**Issue by kgodey** [creativecommons/faq#30]
_This is an Outreachy contribution task. Multiple people may complete this task, it will not be closed until the Outreachy winter 2019 contribution period ends._

---
Review CC’s FAQs and design a user friendly page that incorporates what you believe to be the ten most important ones. Make a new folder in this repository with your HTML and CSS files and submit it as a pull request.

Usage of [CC Vocabulary](https://opensource.creativecommons.org/cc-vocabulary/) is recommended but not required.

**Comment by cthomas88** [comment]
I would like to assist with this project if possible, I have created some wonderful looking FAQ sections on my own websites and think I could assist quite well here. Carlie, UK based Outreachy intern applicant.

**Comment by kgodey** [comment]
Sounds great!

**Comment by thelittleveggiekorean** [comment]
Hello. I am Chohee, an Outreachy applicant. I Would love to work on this project :)

**Comment by mbengtanyi** [comment]
Hello @kgodey 
I'd like to contribute to this issue.
Is it obligatory to use the standard cc faq template for this?

**Comment by ifylala** [comment]
Hello I am Ify an Outreachy applicant, I would also love to work on this issue

**Comment by mmoreshead** [comment]
@mbengtanyi - there is no need to stick to the standard template, we're happy to see whatever you wish to create!

**Comment by kgodey** [comment]
Everyone – go ahead and work on the issue and submit a PR.

**Comment by cthomas88** [comment]
If we feel we could recreate all of the questions in a concise and easy to use format would that be ok, rather than narrow down to 10? It would be easier for the client if their question was accessible rather than only a few.

**Comment by kgodey** [comment]
The idea behind this task was to make a smaller task without you having to do all the work of porting the full FAQ if we didn't go with the solution proposed. If you'd like to do more than 10, go ahead, but keep in mind we may not use your work.

**Comment by chidexebere** [comment]
Hello @kgodey , I am an Outreachy applicant and would love to contribute to this project. I know Creative Commons uses Vue as stated in the CC Vocabulary  but I wanted to clarify if I can use any other JS library or framework for this task

**Comment by kgodey** [comment]
@chidexebere for this task, you can use any JS library or framework since this is just a demonstration of your skills but we recommend integration with CC Vocabulary

**Comment by stephaniiii** [comment]
Hello @kgodey
I'd like to contribute to this issue.
If it is possible.

**Comment by kgodey** [comment]
go ahead

**Comment by thelittleveggiekorean** [comment]
Hi @kgodey I've got a question on this issue :) I saw there are lots of questions that seem to important for many users. Should I make a page which only shows up the the most important 10 questions? or shows the other questions too in one page?

**Comment by kgodey** [comment]
@thelittleveggiekorean Pick 10 that seem important to you

**Comment by moshinaakter** [comment]
Hello Kgodey, I am Moshina an Outreachy applicant, I would love to work on this issue.

**Comment by kgodey** [comment]
@moshinaakter go ahead

**Comment by ifylala** [comment]
@kgodey Here is the url to the deployment I made on github pages 
https://ifylala.github.io/CreativeCommonFaq kindly review

**Comment by annatuma** [comment]
@ifylala thank you for contributing, that's an interesting layout! Definitely include some of your design ideas and rationale in your upcoming final application for the project.

**Comment by ifylala** [comment]
> @ifylala thank you for contributing, that's an interesting layout! Definitely include some of your design ideas and rationale in your upcoming final application for the project.

Thanks for the feedback @annatuma . Does it mean i have successfully contributed to this issue?

**Comment by kgodey** [comment]
@ifylala yes!

**Comment by moshinaakter** [comment]
@kgodey this is my initial contribution of Creative Commons 10 most important FAQs which I made on github page.  Please review the URL below.
https://moshinaakter.github.io/CC-FAQ-Template/

**Comment by moshinaakter** [comment]
Hello Kgodey what will be the next steep for me, pls tell. Now Can I apply for Record contribution and Final Application or any more work i need to be complete as an Outreacy intern applicant? 
Thanks

**Comment by kgodey** [comment]
Nice work @moshinaakter! You can record that as a contribution and start work on your final application, as we discussed on Slack.

**Comment by moshinaakter** [comment]
Ok thanks for your feedback @kgodey 
I will proceed for next steep asap.

**Comment by kgodey** [comment]
Since the Outreachy application period is over, I'm going to close this issue.
