### ISSUE TITLE
Create a short video answering an FAQ

### ISSUE THREAD

**Issue by kgodey** [creativecommons/faq#33]
_This is an Outreachy contribution task. Multiple people may complete this task, it will not be closed until the Outreachy winter 2019 contribution period ends._

---
Create a short video (which does not have to be fancy!) that answers a particularly important CC FAQ. Post the link to your video here.

**Comment by ifylala** [comment]
Hi @kgodey here is the link to the short video I created https://promo.com/share/5d95fd538dad8e528c6dbd40?utm_source=v1_shareDialog2_copy

**Comment by kryptosjay-code** [comment]
hello @kgodey here is a link to CC FAQ short video I created
https://www.renderforest.com/watch-21266447?queue=17615790&utm_source=email&utm_medium=export&utm_campaign=export_finished_email_thumb

**Comment by tyanastone** [comment]
@kgodey  @mmoreshead Here is the link to the video I've created. It's on YouTube as unlisted so only people with the link can view it. It's not public. For future videos, I would like to add a voice-over to read the question and answers. 

[CC FAQ VIDEO](https://youtu.be/zsr96ktpmv0)

**Comment by mmoreshead** [comment]
Fun videos, everyone!

**Comment by mmoreshead** [comment]
Have you thought about using CC licensed images or music in your videos?

**Comment by ifylala** [comment]
> Have you thought about using CC licensed images or music in your videos?

Nice suggestion @mmoreshead I'd try adding that. Thanks for the tips

**Comment by kryptosjay-code** [comment]
that actually didnt cross my mind but let me try that now

> 
> 
> Have you thought about using CC licensed images or music in your videos?

@mmoreshead that didn't cross my mind let me try that now, thanks for the heads up

**Comment by tyanastone** [comment]
> Have you thought about using CC licensed images or music in your videos?

@mmoreshead CC was one of the many places I tried searching because I initially wanted to use different software to make the video, but I wasn't able to find the specific type of animations I was looking for on the CC site, I may just need better practice with searching through the site though.

**Comment by mmoreshead** [comment]
@tyanastone there are lots of sites that host CC licensed material, not just cc.org!

**Comment by kgodey** [comment]
@ifylala @kryptosjay-code @tyanastone those are fun videos, good effort! However, the aim of this task is to create an informative video that answers a question from our FAQ: https://creativecommons.org/faq/ and should contain the full information from one of our FAQs. I would recommend emphasizing content over style.

**Comment by AndrejaP** [comment]
Hello! I'm glad to have done this task because I discovered a new passion :). I came here to post my videos and then I read that they should contain the full information from one of the FAQ  :O. I adjusted one of them and now it contains the full answer from the CC website to the question: Can I take a CC-licensed work and use it in a different format? Here is the link: https://www.youtube.com/watch?v=Q3MAt3hM_eg

**Comment by mmoreshead** [comment]
> > Have you thought about using CC licensed images or music in your videos?
> 
> @mmoreshead CC was one of the many places I tried searching because I initially wanted to use different software to make the video, but I wasn't able to find the specific type of animations I was looking for on the CC site, I may just need better practice with searching through the site though.

Hey @tyanastone -- there are many many websites that host CC licensed content. Try vimeo or the internet archive or soundcloud or the free music archive!

**Comment by ifylala** [comment]
@kgodey @mmoreshead kindly check the video I created https://www.renderforest.comwatch-21455598

**Comment by ifylala** [comment]
@kgodey @mmoreshead  Kindly review https://www.youtube.com/watch?v=vmHy6RVwltQ&feature=youtu.be

**Comment by annatuma** [comment]
@ifylala the video is listed as private, I recommend making it viewable but unlisted, as @tyanastone did.

@AndrejaP thanks for your submission. I'd suggest thinking about how much and how easily someone viewing the video can learn. While graphics and music are great, a simpler approach may be more meaningful. That said, I'm sure this task has given you plenty of things to think about regarding the larger project, and we look forward to seeing the final application.

**Comment by ifylala** [comment]
> @ifylala the video is listed as private, I recommend making it viewable but unlisted, as @tyanastone did.
> 
> @AndrejaP thanks for your submission. I'd suggest thinking about how much and how easily someone viewing the video can learn. While graphics and music are great, a simpler approach may be more meaningful. That said, I'm sure this task has given you plenty of things to think about regarding the larger project, and we look forward to seeing the final application.

@annatuma I have made made it viewable. kindly review.

**Comment by AndrejaP** [comment]
@annatuma thanks a lot for the feedback. I see your point. I should focus more on user experience.

**Comment by ifylala** [comment]
@kgodey @mmoreshead Kindly review https://www.youtube.com/watch?v=vmHy6RVwltQ&feature=youtu.be

**Comment by kgodey** [comment]
@ifylala thank you for contributing! I have similar feedback as @annatuma had for @AndrejaP – I'd suggest thinking more about the user experience of someone learning about CC through the video. It would be great if the video focused more on explaining the answer rather than showing the same text as the FAQ with graphics and music. However, this counts as your contribution and we hope that it helps you towards your final application.

**Comment by moreinob** [comment]
This video answers the question "what is creative commons"
https://m.facebook.com/story.php?story_fbid=2378324619098878&id=1885614538369891

**Comment by kgodey** [comment]
Nice work @moreinob! I like the narration. I hope that your contribution helps in your Outreachy final application, let us know if you have any questions about the project.

**Comment by GettyOrawo** [comment]
Hello. :slightly_smiling_face:  Here's  my video answering the question "Where can I find material offered under a CC Licence"
https://promo.com/share/5dc0fb628dad8e2da65f93f4?utm_source=v1_shareDialog2_copy

**Comment by kgodey** [comment]
Nice work @GettyOrawo!

**Comment by mbengtanyi** [comment]
For some reason, I interpreted this issue to mean an actual person literally talking about a particular FAQ. I see it differently now from the contributions already made here.

**Comment by kgodey** [comment]
@mbengtanyi an actual person literally talking about an actual FAQ would be great.

**Comment by kgodey** [comment]
Since the Outreachy application period is over, I'm going to close this issue.
