### ISSUE TITLE
Demo knowledge base software

### ISSUE THREAD

**Issue by kgodey** [creativecommons/faq#34]
_This is an Outreachy contribution task. Multiple people may complete this task, it will not be closed until the Outreachy winter 2019 contribution period ends._

---
Enter some of CC’s FAQs into a knowledge base software so that they can be searched by keywords. Please make clear that it is not official CC FAQs and just a test project. Post the link to this knowledge base here.

**Comment by mchesler613** [comment]
@kgodey Hi, are we restricted to free versions of this knowledge base software, or can use a free-trial version of commercial software?  Thanks.

**Comment by mchesler613** [comment]
Hi @kgodey, I have created a Knowledge Base software on my domain and installed several FAQs under different headings.  Please take a look, http://moriahweb.com/cc.  The site is searchable and I have also tested the headings using AP-style titling here, https://capitalizemytitle.com/#.  Please check it out and let me know if you want more FAQs in there.  This site is not backed up.

**Comment by kgodey** [comment]
@mchesler613 Thank you, looks good to me. I don't have specific feedback, the purpose of this task was as partial research for the final application.

**Comment by kgodey** [comment]
Since the Outreachy application period is over, I'm going to close this issue.
