### ISSUE TITLE
Broken link in FAQ

### ISSUE THREAD

**Issue by kgodey** [creativecommons/faq#46]
Email from user:

> Hi, I just wanted to bring your attention to a broken link:
> https://creativecommons.org/faq/ 
> under this question:
> 
> **What if I change my mind about using a CC License?**
> 
> There's a link to this: https://creativecommons.org/faq/Considerations%20for%20licensors%20and%20licensees
> I believe the correct link is one of these, but I'll let you sort that out:
> https://wiki.creativecommons.org/wiki/Considerations_for_licensors_and_licensees 
> or 
> https://creativecommons.org/share-your-work/licensing-considerations/version4/

**Comment by peterspdx** [comment]
We want it to match the link from the legal code for 4.0, which at present is: https://wiki.creativecommons.org/wiki/Considerations_for_licensors_and_licensees#Considerations_for_licensors

We have talked about moving this very important page to the main side in wp, but unsure if that was fully completed. If so (i.e., the text is the same), then this requires changing the links in the prefaces to all 4.0 licenses, or creating a redirect from the wiki page to the main site.

@sarahpearson Other thoughts?

**Comment by sarahpearson** [comment]
I agree. For now, the link in the FAQ should point to https://wiki.creativecommons.org/wiki/Considerations_for_licensors_and_licensees#Considerations_for_licensors

As Diane indicates, we eventually want that page moved to WordPress and have talked about doing that for a long time. I am not sure who would handle that sort of task. If it is as simple as making a new Wordpress page, I can certainly do it. But I previously thought it was tied up in other infrastructure projects around how to make those materials translatable, etc. If you want me to just move it to WordPress, let me know!
