### ISSUE TITLE
Clarify some points in light of CC0

### ISSUE THREAD

**Issue by aucampia** [creativecommons/faq#47]
## Problem Description

I know the CC0 has it's own FAQ - but some phrases in the FAQ is unclear to me at least on whether they apply to CC0 or not.

> All CC licenses are non-exclusive: creators and owners can enter into additional, different licensing arrangements for the same material at any time (often referred to as “dual-licensing” or “multi-licensing”). However, CC licenses are not revocable once granted unless there has been a breach, and even then the license is terminated only for the breaching licensee.

I'm no lawyer, and I don't quite know if dual-licensing of CC0 is possible or not or if the public domain dedication is exclusive or not. I think if the text above does not apply to CC0 (which I think it may not) then it should be made clearer.

## Proposed Solution

Make it clear whether CC0 is included in statements like "All CC licenses"

**Comment by sarahpearson** [comment]
Thank you for raising this. CC0 is not a license (or to be more precise, it is a license if and only if the public domain dedication is unenforceable in a given jurisdiction). That means it does not operate in the same way as the licenses in this regard. If CC0 is applied to a work, the work is no longer subject to copyright, so it wouldn't be appropriate to apply a CC license to it. We will update this FAQ that you cited here to make this clear.

**Comment by Abbas-000** [comment]
I am an outreachy applicant can I work on this?

**Comment by sarahpearson** [comment]
Thanks, but this one will have to be handled by CC's legal department.
