### ISSUE TITLE
Fix font sizes of headings so uniform throughout in English FAQs

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/faq#9]
The actual FAQ question and any subsection header should be larger than the text of the answer, and the main section header still larger. 

Here is an example of getting it right:

For Licensors is larger than the subsection heading "Choosing a license", and that the actual question "What things should I think about before I apply a Creative Commons license?" are larger than the text of the answer.

Here is an example of where it's wrong -- appears to just be under the Data FAQs. But, e.g., this question: Can databases be released under CC licenses?, is the same font size as the text of the answer, as is the case thereafter.

Additional comment: note that this is different than the French. In the French, the Section header is largest, then the Subsection  header, and then the question. E.g, 
Choisir une licence (Section header is largest)
Pour les concédants de licence (Subsection header is smaller)
A quoi penser avant de demander une licence Creative Commons (question is still smaller)

Would be nice if the French and the English were the same.

**Comment by mattl** [comment]
What is "For Licensors" in this case? A section heading?

**Comment by peterspdx** [comment]
Yes, it was referring to the section header in the English, For Licensors.

You got this all fixed. Thanks.
